services:
  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis_standalone
    hostname: localhost
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379